### ISSUE TITLE
Splinter Cell - Double Agent on RGH360 XEFU - Saves still corrupted

### ISSUE THREAD

**Issue by ajalberd** [feudalnate/Original-Xbox-Gamesave-Resigners#1]
Hello,

I just tried the tool using the HDD key generated from the serial and MB, but am still getting the "savefile corrupted" error 
HDD KEY: 00000000750092620558233531353032

When signing a profile from an OGXBOX with nullified EEPROM:
Current   : C9747F5BC5A16268CACBB7B04EC6C2ACCC15206E
Calculated: B660D9E64A57110586EF88A37D01F195AE0A9224

When signing a profile created by the 360:
Current   : B5CD25C99568EDB3098D76408E438F848E590832
Calculated: 3F853A4D2BC44A96EFC85A548FBF957EDB252F70

Is there a way to get the HDD key from a savefile to verify that that actually is my HDD key? Any insight would be greatly appreciated!

**Comment by feudalnate** [comment]
I will look into it, could you provide a "clean" copy of the save file(s) you're working with? (a copy of the file(s) you haven't already tried to sign)

Also, could you clarify you're using the original Xbox version of the game on your Xbox 360 and not the Xbox 360 version of the game (I'm assuming you're using the original Xbox version since you mentioned the fusion emulator but just to confirm)

There's no way to reverse the original XboxHDKey used to sign save data from existing save files. You can verify the XboxHDKey is correct for a console by signing DLC or an update file for a game and check the game is displaying the content/update properly

**Comment by ajalberd** [comment]
Yep, the game is Double Agent for the original XBOX. I am playing on a RGH unlocked Xbox 360 with the latest Xefu files. So not sure what that impacts.

[Here](https://drive.google.com/file/d/1BkfAyALOmdqZRVhMl43jaof5PG3vJt-i/view?usp=sharing) is a few saves, there are 3. 

> There's no way to reverse the original XboxHDKey

Dang, I assumed as much by looking at the terminal output. 

> You can verify the XboxHDKey is correct for a console by signing DLC or an update file for a game

Wonder what the easiest way to test that is... Thank you again for your reply and insight!

**Comment by feudalnate** [comment]
I tested out a set of the saves you provided (07C50AD0A46B folder) and [was able to sign and load them](https://imgur.com/a/gusCJny) on my console. The files I tested were "profile.sav", "multi0.sav", "multi0image.sav", "single0.sav", and "single0image.sav"

Splinter Cell: Double Agent must have the corresponding "... image.sav" file signed when signing the actual save file. For example, if you sign "single0.sav" for a specific console then "single0image.sav" must be signed for that console as well or the save file will display as corrupt

Double check your XboxHDKey(s) - you can grab the correct key from a soft modded/hard modded original Xbox fairly easily through a dashboard or app and for your Xbox 360, it might be more beneficial to get the motherboard and console serial numbers from a keyvault (KV.bin) dump

For test signing DLC/updates to check key validity, [you can use another one of my tools](https://github.com/feudalnate/XBX-Content-Tool) to sign content with a given XboxHDKey. You would need to download DLC/updates for a game you have, manually sign the content with a key, and transfer it to your console to test. [A user uploaded a video to YouTube showing a brief tutorial on how to do this](https://www.youtube.com/watch?v=OidWvvXuDIk) - my DLC/update signing tool can also import the XboxHDKey automatically from a decrypted KV.bin dump, which would remove the guess work for you

**Comment by ajalberd** [comment]
Awesome! My knowledge on the 360 is very limited, I had no clue the HDkey was tied to the KV. Read it using that tool and got the actual HDDkey: 00000000725627011858030531353032 . 

Thank you so much for your help.
