### ISSUE TITLE
Can you please check fatal frame?

### ISSUE THREAD

**Issue by dante3732** [feudalnate/Original-Xbox-Gamesave-Resigners#3]
The game  from teсmo and when i try to load save from network, game give me error.

**Comment by feudalnate** [comment]
I can take a look. Could you upload and link your save files?

**Comment by dante3732** [comment]
https://drive.google.com/file/d/1OacFCprMWTAp8bzxIAFq-yyFXfXYV08v/view?usp=sharing it my save.
https://legacy.downloads.diomtec.com/homebrew/warchives/xbox-saves/files/54430004.zip it save from network.

**Comment by dante3732** [comment]
Same in fatal frame 2
[5443000a.zip](https://github.com/feudalnate/Original-Xbox-Gamesave-Resigners/files/8791350/5443000a.zip)
![xemu-2022-05-28-17-57-39](https://user-images.githubusercontent.com/66036249/170830960-d0d29bca-4902-4d29-9245-d16aa5e3e0de.png)

**Comment by feudalnate** [comment]
Thanks for providing saves for reference. For Fatal Frame 2, you must include the "game.xsv" file as well - it can't just be the "header.xsv" file

https://github.com/feudalnate/Original-Xbox-Gamesave-Resigners/tree/master/Fatal-Frame
https://github.com/feudalnate/Original-Xbox-Gamesave-Resigners/tree/master/Fatal-Frame-2

Let me know if you have any issues

**Comment by dante3732** [comment]
In first game save work good.
In second save from network don't work. Maybe because it have only one .xsv. My XBOX save have 2 .xsv files. I take my saves from my xbox and sigh 2 .xsv for cxbxr hddkey and it work.
[5443000a.zip](https://github.com/feudalnate/Original-Xbox-Gamesave-Resigners/files/8792928/5443000a.zip)
![3245](https://user-images.githubusercontent.com/66036249/170859742-fc76780b-e3ac-4495-81e8-8fb44e15c122.jpg)

**Comment by feudalnate** [comment]
I was able to take save files (header.xsv/game.xsv) from one console, sign them for another, and load them successfully on that other console.

I don't believe you can mix and match the "header.xsv" with just any "game.xsv", you need both the "header.xsv" and "game.xsv" files from the same save. So the save you downloaded that only has the "header.xsv" isn't going to work, you need the "game.xsv" file from that save as well

**Comment by dante3732** [comment]
> I was able to take save files (header.xsv/game.xsv) from one console, sign them for another, and load them successfully on that other console.
> 
> I don't believe you can mix and match the "header.xsv" with just any "game.xsv", you need both the "header.xsv" and "game.xsv" files from the same save. So the save you downloaded that only has the "header.xsv" isn't going to work, you need the "game.xsv" file from that save as well

Thanks for work and info. 
It is not clear then what was the point of someone uploading saves for fatal frame 2 with only one file.
